### ISSUE TITLE
Upload to crates.io

### ISSUE THREAD

**Issue by hellow554** [KillingSpark/zstd-rs#1]
Is there any reason why this isn't published on crates.io?

**Comment by KillingSpark** [comment]
Not really. It would be my first publish there and I wanted to get this lib right before I start to experiment with new ways to publish it. It is now in a state where uploading it on crates.io would be a good next/soonish step

**Comment by hellow554** [comment]
You probably want to run `rustfmt` and `clippy` first ^^

**Comment by KillingSpark** [comment]
Yeah just did that :D
I am glad clippy just had issues with the binary part. That was meant to be an example where I didn't worry too much about code quality, everything else was fine

**Comment by KillingSpark** [comment]
Apparently the files from the decodecorpus_files get pulled in by cargo publish which bloats the .crate file over the allowed size. Will need to research how to exclude these.

**Comment by KillingSpark** [comment]
Done!

**Comment by Gowee** [comment]
Thank you, @KillingSpark .

But it is not easy to find this crate on docs.rs. It would be great if the README contains a badge linked to doc.rs.

**Comment by KillingSpark** [comment]
Done :)
