### ISSUE TITLE
Possible crates.io release?

### ISSUE THREAD

**Issue by jam1garner** [KillingSpark/zstd-rs#10]
It seems like the latest version on crates.io (0.2.1) is almost a year old, despite numerous updates to master.

I'd like to depend on this for compatibility on a platform which doesn't have `rand` available, however the crates.io release doesn't disable default features for twox-hash, so I'm currently dependent on master.

Is there any blockers for a new crates.io release, even if it's only a patch release?

**Comment by KillingSpark** [comment]
Hey, there is no real blocker. I'll look into whether this needs a 0.3.0 release or if a 0.2.2 release would be fine and make a new release available on crates.io. I'll get to that tomorrow.

**Comment by KillingSpark** [comment]
There is a v0.2.2 release on crates.io now. I hope this resolves that issue :)

**Comment by jam1garner** [comment]
Thank you! It does! Appreciate the quick response, thanks again for the great crate!
