### ISSUE TITLE
Replace usage of unsafe with Vec::extend_from_within

### ISSUE THREAD

**Issue by paolobarbolini** [KillingSpark/zstd-rs#14]
When [this](https://github.com/rust-lang/rust/issues/81656) will eventually become stable it will allow unsafe to be removed from here:

https://github.com/KillingSpark/zstd-rs/blob/b093adefe3eaf19c89679d595f310d553b8931fa/src/decoding/decodebuffer.rs#L117-L144

I just saw the tracking issue and I immediately remembered your crate could use something like this :smiley:

**Comment by KillingSpark** [comment]
Yep that is basically what this code needs. Good to have an issue for that here too, thanks :)

Do you know how fast these things normally get stabilized? I don't follow new features that closely before they get released.

**Comment by paolobarbolini** [comment]
> Do you know how fast these things normally get stabilized?

It depends on many factors, including if anything new comes up in the next months. For example [`core::slice::fill`](https://doc.rust-lang.org/nightly/std/primitive.slice.html#method.fill) took about 10 months, if we also count the ~3 months it took for two versions to go by for it go get into beta and then finally into stable (source: https://github.com/rust-lang/rust/issues/70758)

If we have nightly users who are really interested into making things like cargo geiger happier, a `nightly` feature could be added to conditionally replace the unsafe function with the safe one.

**Comment by paolobarbolini** [comment]
Looks like this is going to come with 1.53 https://github.com/rust-lang/rust/pull/84642

**Comment by Shnatsel** [comment]
`Vec::extend_from_within` is now stabilized, so the last unsafe block in this codebase can be dropped!

I wrote the [RFC](https://github.com/Shnatsel/rfcs/blob/patch-1/text/0000-vec-append-from-within.md) for `Vec::extend_from_within` with use cases like this in mind, and I'm very happy to see it finally land!

**Comment by KillingSpark** [comment]
this is great! I am not familiar with how this is usually handled. Is it ok to just require all my users to have rustc with the latest version available or do I do a conditional compilation for some time and remove the unsafe code at a later time?

**Comment by Shnatsel** [comment]
Long story short, there is no clear consensus.

https://crates.io/crates/rustversion is used by `quote`, `thiserror`, `anyhow` and other major crates. It provides conditional compilation.

Some widely used libraries take the conservative approach and only use functions requiring a newer stdlib after the required version has [percolated everywhere](https://pkgs.org/search/?q=rustc).

On the other end of the spectrum, some projects explicitly require the latest compiler at all times and don't support anything else.

**Comment by KillingSpark** [comment]
Well I guess since this is the only update and I don't see any big other changes in the nearish future, just making a new release stating that this only trades support for older compiler for removing of unsafe code should be fine. 

People requiring older compilers can just use the older version then, it's functionally equivalent.

**Comment by CodesInChaos** [comment]
Perhaps add `#![forbid(unsafe_code)]` to the crate now?

**Comment by KillingSpark** [comment]
Done! I think that concludes this issue :)
