### ISSUE TITLE
Use Byteorder or std instead of manual shifting

### ISSUE THREAD

**Issue by hellow554** [KillingSpark/zstd-rs#3]
https://github.com/KillingSpark/zstd-rs/blob/1f6749d700f82697584c809b4ca81eeab1bf96bb/src/decoding/scratch.rs#L74-L77

There are numerous places like these, where you manually create a integer from bytes. 
You should either use the Byteorder crate (which is already in the dependencies and rarely used) or use the std variants [`{from,to}_{le,be,ne}_bytes`](https://doc.rust-lang.org/std/primitive.isize.html#method.from_be_bytes).

**Comment by KillingSpark** [comment]
I'll look into the std lib's functions. I'd like to avoid the byteorder crate as much as possible to reduce the amount of unsafe code used. I juts pulled it in because it introduced a big performance boost

**Comment by KillingSpark** [comment]
I moved all of this into one module decoding::little_endian (which I should have done in the first place...)
