### ISSUE TITLE
Make RingBuffer Send and Sync

### ISSUE THREAD

**Issue by Manorhos** [KillingSpark/zstd-rs#56]
`FrameDecoder` is currently [!Send and !Sync](https://docs.rs/ruzstd/latest/ruzstd/frame_decoder/struct.FrameDecoder.html#impl-Send-for-FrameDecoder) due to `core::ptr::NonNull` [being as such](https://doc.rust-lang.org/core/ptr/struct.NonNull.html#impl-Send-for-NonNull%3CT%3E).

I think it would be alright to add `Send` and `Sync` impls for `RingBuffer` as I don't see any way that memory held by the buffer could be aliased or any interior mutability used in the struct.
Could you please check this and consider making `RingBuffer` `Send` and `Sync`?

**Comment by KillingSpark** [comment]
I don't see why it shouldn't be Send + Sync. I'll add those impls.

Out of curiosity, how did this come up?

**Comment by KillingSpark** [comment]
Could you confirm that a16e38be5c94279a9ab8890f4eb8578acacad006 resolves this issue before I make a new release?

**Comment by Manorhos** [comment]
Yeah, thanks, that works!

[chd-rs](https://github.com/SnowflakePowered/chd-rs) recently added support for CHDs that use Zstandard compression, and `Chd` lost the Send + Sync markers because `FrameDecoder` is kept as state.

In my image access crate I've been [moving the `Chd` to another thread](https://github.com/Manorhos/imageparse/blob/5606b383c4d293dcc359777bee21ad9c15fd9a56/src/chd/chd_thread.rs#L53-L55), but that broke because it's no longer Send.

**Comment by KillingSpark** [comment]
Released as 0.6.0 because other pending were potentially breaking based on crate features. So chd-rs will need to update their ruzstd dependency :/

**Comment by Manorhos** [comment]
Thanks and no problem, it has to be made explicit on `CompressionCodec` anyway.
